export type PostBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'ul'; items: string[] }

export interface Post {
  slug: string
  title: string
  excerpt: string
  category: string
  readTime: string
  date: string
  tags: string[]
  content: PostBlock[]
}

export const POSTS: Post[] = [
  {
    slug: 'stripe-openrouter-openai-preparedness',
    title: 'Stripe Buys OpenRouter; OpenAI Disbands Preparedness Team',
    excerpt: 'Stripe acquires AI gateway OpenRouter for $7M+ to accelerate LLM monetization, while OpenAI dissolves its Preparedness safety team — infrastructure consolidates as oversight shrinks.',
    category: 'AI',
    readTime: '4 min',
    date: '2026-08-17',
    tags: ['AI', 'Industry', 'Infrastructure', 'Safety'],
    content: [
      { type: 'p', text: 'Two contrasting signals this week: payments giant Stripe doubling down on AI infrastructure, while the frontier lab with the most deployed models quietly reduces its internal safety capacity.' },
      { type: 'h2', text: 'Stripe acquires OpenRouter' },
      { type: 'p', text: 'Stripe confirmed the acquisition of OpenRouter, the popular AI model gateway that lets developers route requests across 100+ models through a single API. The deal, reportedly $7M+, gives Stripe instant distribution into the LLM developer ecosystem and a path to monetize model usage through its payments rails — usage-based billing, invoicing, and payouts for model providers.' },
      { type: 'p', text: 'For developers, this means the gateway layer is becoming payments-aware. Expect tighter integration: one API key, unified billing across models, and Stripe-level reliability on the routing layer. For model providers, it is a new distribution channel with built-in monetization.' },
      { type: 'h2', text: 'OpenAI disbands Preparedness team' },
      { type: 'p', text: 'OpenAI dissolved its Preparedness team — the internal group tasked with evaluating catastrophic risks from frontier models (cyber, bio, persuasion, autonomy). Researchers were reassigned; the team lead departed. The Verge reports this follows a pattern: safety oversight structures created under pressure are being streamlined as commercialization accelerates.' },
      { type: 'p', text: 'The team\'s framework (the "Preparedness Framework") scored model capabilities against risk thresholds. Its dissolution does not mean scoring stops — but it moves from a dedicated team to distributed ownership, which historically weakens accountability.' },
      { type: 'h2', text: 'What this means for builders' },
      { type: 'ul', items: [
        'Model routing is consolidating — gateways with payments rails win; single-model dependencies are a liability',
        'Safety evals are becoming a buyer responsibility — do not assume the model provider caught it',
        'Infrastructure plays (Stripe, gateways, eval platforms) are capturing value that used to sit at the model layer',
        'Commodity intelligence + payments infrastructure = new business models for AI-native products',
      ]},
      { type: 'p', text: 'The stack is settling: models become interchangeable, routing becomes the product, and whoever owns the developer relationship (and the billing) sets the terms.' },
    ],
  },
  {
    slug: 'anthropic-watermark-autonomous-trucks-california',
    title: 'Anthropic Watermark & Autonomous Trucks Hit California Roads',
    excerpt: 'Anthropic reveals technical details of Claude watermark system as Aurora and Kodiak get California permits for driverless truck testing — transparency and deployment milestones.',
    category: 'AI',
    readTime: '4 min',
    date: '2026-08-16',
    tags: ['AI', 'Industry', 'Autonomous Vehicles', 'Transparency'],
    content: [
      { type: 'p', text: 'Two significant developments this week mark a maturing AI landscape: Anthropic opening up about content provenance, and autonomous freight moving from test tracks to public California highways.' },
      { type: 'h2', text: 'Anthropic lifts the lid on Claude watermarks' },
      { type: 'p', text: 'Anthropic published technical details of their new watermarking system for Claude-generated text — including how it survives editing and its impact on code output. This is part of a broader push for AI content transparency, giving platforms and users a way to detect AI-originated content without relying on unreliable classifiers.' },
      { type: 'p', text: 'The watermark works by subtly biasing token probabilities during generation, creating a statistical fingerprint detectable with the right key. Anthropic claims it survives light editing, paraphrasing, and translation — though heavy rewriting degrades detection. For code, the watermark minimally affects correctness but may shift style preferences.' },
      { type: 'h2', text: 'Driverless trucks cleared for California highways' },
      { type: 'p', text: 'Aurora Innovation and Kodiak Robotics received permits from the California DMV to test fully driverless heavy-duty trucks on public roads — not closed courses. This is a regulatory milestone: the first time autonomous freight shares lanes with regular traffic at scale in the state.' },
      { type: 'p', text: 'Logistics is an $800B+ industry in the US alone. The players who solve the last 10% of edge cases — weather, construction zones, human driver interaction — will capture massive value. The core tech is largely there; deployment and reliability are now the product.' },
      { type: 'h2', text: 'What this means for product teams' },
      { type: 'ul', items: [
        'Content provenance is becoming infrastructure — expect watermark detection APIs to standardize across platforms',
        'Model costs keep falling — build assuming cheap intelligence, not expensive API calls',
        'Physical-world AI (robotics, autonomy, logistics) is the next deployment frontier — software-only moats are eroding',
        'Differentiation moves up the stack: evals, guardrails, orchestration, and domain data',
      ]},
      { type: 'p', text: 'The pattern is clear: intelligence becomes infrastructure, and the value accrues to whoever wraps it into reliable, domain-specific workflows.' },
    ],
  },
  {
    slug: 'ai-price-war-autonomous-trucks',
    title: 'AI Price War & Autonomous Trucks Hit the Road',
    excerpt: 'OpenAI and Anthropic slash API prices as Chinese rivals rise, while driverless trucks begin California highway testing — signaling a new phase in AI deployment.',
    category: 'AI',
    readTime: '4 min',
    date: '2026-08-15',
    tags: ['AI', 'Industry', 'Autonomous Vehicles'],
    content: [
      { type: 'p', text: 'Two major shifts landed this week that signal where the AI market is heading: a full-blown price war at the model layer, and autonomous freight moving from test tracks to public highways.' },
      { type: 'h2', text: 'The API price war is real' },
      { type: 'p', text: 'OpenAI and Anthropic are cutting API prices in direct response to Chinese competitors — DeepSeek, Alibaba, and others — who are delivering comparable intelligence at a fraction of the cost. The economics of frontier models are shifting from "premium for capability" to "commodity pricing with differentiation at the edges."' },
      { type: 'p', text: 'For builders, this means the cost of intelligence is dropping fast. The moat is no longer raw model access — it is workflow integration, eval infrastructure, and domain-specific tooling that makes models actually useful in production.' },
      { type: 'h2', text: 'Driverless trucks on California highways' },
      { type: 'p', text: 'TechCrunch reports that autonomous trucks are now being tested on public California roads — not closed courses. This is a regulatory and operational milestone: the first time heavy-duty driverless freight shares lanes with regular traffic at scale.' },
      { type: 'p', text: 'Logistics is a $800B+ industry in the US alone. The players who solve the last 10% of edge cases (weather, construction zones, human driver interaction) will capture massive value. The tech is largely there; the deployment is the product now.' },
      { type: 'h2', text: 'What this means for product teams' },
      { type: 'ul', items: [
        'Model costs will keep falling — build assuming cheap intelligence, not expensive API calls',
        'Differentiation moves up the stack: evals, guardrails, orchestration, and domain data',
        'Physical-world AI (robotics, autonomy, logistics) is the next deployment frontier — software-only moats are eroding',
      ]},
      { type: 'p', text: 'The pattern is clear: intelligence becomes infrastructure, and the value accrues to whoever wraps it into reliable, domain-specific workflows.' },
    ],
  },
  {
    slug: 'shipping-at-ai-speed',
    title: 'Shipping at AI Speed: How We Cut Delivery Time by 60%',
    excerpt: 'Our AI-native workflow — from spec to production — and the tools that make it possible.',
    category: 'Engineering',
    readTime: '8 min',
    date: '2025-01-15',
    tags: ['AI', 'Workflow', 'Delivery'],
    content: [
      { type: 'p', text: 'Agencies that treat AI as a chatbot are missing the point. The real win is restructuring the entire delivery pipeline so humans direct and agents execute. We did this in 2024 and cut average project delivery from 14 weeks to under 6.' },
      { type: 'h2', text: 'Where the time actually went' },
      { type: 'p', text: 'We audited every project from the past two years. The breakdown was consistent: 20% discovery, 15% design, 30% development, 25% QA and fixes, 10% deployment and handoff. The biggest leak was not development — it was context switching between phases.' },
      { type: 'p', text: 'A design handoff to a developer who has never seen the Figma file costs roughly two days of ramp-up. Multiply that across every phase boundary and the waste compounds.' },
      { type: 'h2', text: 'The AI-native pipeline we use now' },
      { type: 'ul', items: [
        'Discovery: AI-synthesized research notes, journey maps, and a living PRD generated from every call transcript',
        'Design: token-first systems where components map 1:1 to code primitives, so agents can implement without guessing',
        'Development: agents handle boilerplate, CRUD, tests, and migrations; humans review diffs and own architecture',
        'QA: autonomous agents run regression suites on every commit, with humans only triaging failures',
        'Deployment: one command ships to staging, screenshots every route, and opens a review link',
      ]},
      { type: 'h2', text: 'The 60% number, explained' },
      { type: 'p', text: 'It is not faster developers. It is fewer handoffs, zero waiting on dependencies, and no rework from miscommunication. The spec IS the source of truth, and both humans and agents read the same file.' },
      { type: 'p', text: 'The tools matter less than the workflow. But for what it is worth: Cursor for coding, Figma with token plugins, GitHub Actions for CI, and Vercel for instant previews. Everything else is discipline.' },
    ],
  },
  {
    slug: 'design-systems-that-scale',
    title: 'Design Systems That Actually Scale',
    excerpt: 'Why most design systems fail, and how we build ones that developers love to use.',
    category: 'Design',
    readTime: '6 min',
    date: '2025-01-08',
    tags: ['Design Systems', 'Tokens', 'React'],
    content: [
      { type: 'p', text: 'Most design systems are documentation projects wearing a component library costume. They start with a figma file, become a storybook nobody visits, and die when the team is too busy to update forty components for a new brand color.' },
      { type: 'h2', text: 'The failure mode' },
      { type: 'p', text: 'Design systems fail when they are owned by design, implemented by engineering, and used by neither. The designers keep designing in a vacuum. The engineers rebuild components because the documented ones do not fit. The system becomes an audit trail, not a tool.' },
      { type: 'h2', text: 'What actually works' },
      { type: 'ul', items: [
        'Tokens first: color, spacing, type, and motion live as code. Figma reads the tokens; the app reads the tokens. No drift by construction.',
        'One source of truth: the component library is the spec. Figma mirrors it, not the other way around.',
        'Designers ship code: designers on our team prototype in React, not just Figma. It removes the handoff tax entirely.',
        'Kill the unused: every quarter, delete components with zero usage in the last 90 days. Size is a feature.',
      ]},
      { type: 'h2', text: 'The payoff' },
      { type: 'p', text: 'A system that scales is boring. New pages take hours, not weeks. Brand updates are a token change. New hires are productive on day two because the primitives are small and consistent. Boring is the goal.' },
    ],
  },
  {
    slug: 'autonomous-qa-agents',
    title: 'Autonomous QA Agents: Beyond Testing',
    excerpt: 'How AI agents are transforming quality assurance from a gate to a continuous process.',
    category: 'AI',
    readTime: '10 min',
    date: '2025-01-02',
    tags: ['AI', 'QA', 'Testing'],
    content: [
      { type: 'p', text: 'Traditional QA is a gate: code freezes, testers click for two weeks, bugs come back, everyone argues about severity. Autonomous QA agents flip this into a continuous loop that runs on every commit.' },
      { type: 'h2', text: 'What agents can actually do today' },
      { type: 'ul', items: [
        'Write and maintain regression suites from user stories, not from code — they test intent, not implementation',
        'Explore edge cases humans skip: empty states, slow networks, weird locales, keyboard-only navigation',
        'Verify fixes in the deployed preview, not just the local branch',
        'Generate accessibility reports with concrete selectors and suggested fixes',
        'Track visual regressions pixel-by-pixel across breakpoints',
      ]},
      { type: 'h2', text: 'What they cannot do (yet)' },
      { type: 'p', text: 'Agents are terrible at judging product feel. Whether an empty state is charming or broken, whether a transition is snappy or sluggish — that is still human judgment. The skill is knowing which layer to trust.' },
      { type: 'h2', text: 'The workflow we ship' },
      { type: 'p', text: 'On every pull request: agents run smoke tests, visual diffs, and accessibility scans in parallel with CI. The human reviewer gets a single summary — what broke, where, and a suggested fix. Time-to-review dropped from hours to minutes, and escaped bugs dropped by 40%.' },
    ],
  },
  {
    slug: 'radical-transparency-pricing',
    title: 'Radical Transparency in Agency Pricing',
    excerpt: 'Why we publish our rates, and how it leads to better client relationships.',
    category: 'Business',
    readTime: '5 min',
    date: '2024-12-28',
    tags: ['Business', 'Pricing', 'Agency'],
    content: [
      { type: 'p', text: 'Agencies treat pricing like a state secret. Rate cards are hidden, proposals are theater, and clients discover the real cost three invoices in. We publish our starting prices on the site. It works better for everyone.' },
      { type: 'h2', text: 'What transparency buys you' },
      { type: 'ul', items: [
        'Better leads: the clients who reach out already know the budget range. No wasted discovery calls on either side.',
        'Trust: when the price on the page matches the invoice, the client stops looking for the catch.',
        'Speed: scope conversations start from a shared baseline instead of a surprise.',
      ]},
      { type: 'h2', text: 'The honest part' },
      { type: 'p', text: 'Published prices are starting points, not quotes. Scope changes pricing, and we say so plainly. The transparency is about the system, not a guarantee that every project costs the same. Clients respect that.' },
      { type: 'p', text: 'Radical transparency is a retention strategy disguised as a pricing strategy. The clients who fit are the ones who stay.' },
    ],
  },
  {
    slug: 'react-server-components-mental-model',
    title: 'React Server Components Mental Model',
    excerpt: 'When to use RSC, client components, and streaming. Mental models over rules.',
    category: 'Engineering',
    readTime: '12 min',
    date: '2024-12-20',
    tags: ['React', 'Next.js', 'Architecture'],
    content: [
      { type: 'p', text: 'Server components caused more confusion than any React feature in years, mostly because everyone reached for rules ("use client at the top" ) instead of a mental model. Here is the model: think about where the data lives, not where the code runs.' },
      { type: 'h2', text: 'The one question' },
      { type: 'p', text: 'Ask: does this component need interactivity, or does it need data? If it renders data from a database or API and does not respond to user input, it belongs on the server. If it has state, event handlers, or browser APIs, it belongs on the client.' },
      { type: 'h2', text: 'The boundary is a decision, not a file' },
      { type: 'p', text: '"use client" is not a component type. It is a cut line: everything below it in the tree becomes a client component. The skill is choosing the cut line so the client bundle stays small and the data fetching stays on the server.' },
      { type: 'ul', items: [
        'Fetch in server components; pass data down as props',
        'Keep interactive leaves small — a button, a form, a carousel',
        'Stream with Suspense so slow queries do not block the fast parts of the page',
        'Shared layout that never changes can stay server-rendered with interactive islands inside',
      ]},
      { type: 'h2', text: 'The practical test' },
      { type: 'p', text: 'Open the network tab. If your HTML carries the data and the JS bundle is tiny, you are doing it right. If the client downloads everything to render a static list, the cut line is in the wrong place.' },
    ],
  },
  {
    slug: 'saas-playbook-0-to-10k',
    title: 'From 0 to 10K MRR: Our SaaS Playbook',
    excerpt: 'Pricing, positioning, onboarding, and retention. The exact framework we use with clients.',
    category: 'Business',
    readTime: '15 min',
    date: '2024-12-12',
    tags: ['SaaS', 'Growth', 'Playbook'],
    content: [
      { type: 'p', text: 'We have helped twelve SaaS companies reach $10K MRR. The paths differ, but the framework is always the same. It fits on one page.' },
      { type: 'h2', text: 'Positioning before product' },
      { type: 'p', text: 'Every company that reached $10K MRR solved one painful problem for one specific persona. The ones that failed tried to be a platform. Narrow beats broad until you have revenue, then you expand.' },
      { type: 'h2', text: 'Pricing is a feature' },
      { type: 'ul', items: [
        'Charge for outcomes, not seats, when you can',
        'Raise prices every time you ship something meaningfully better — your best customers will not leave',
        'Annual plans with a discount convert better than monthly-only, and cash flow improves',
      ]},
      { type: 'h2', text: 'Onboarding is the product' },
      { type: 'p', text: 'The first session decides everything. Get the user to their aha moment in under five minutes. That means ruthless simplification of signup, template presets, and sample data that shows the value immediately.' },
      { type: 'h2', text: 'Retention beats acquisition' },
      { type: 'p', text: 'At $10K MRR, churn of 5% means you need $500 of new MRR every single month just to stand still. The companies that win obsess over the weekly active user, not the signup count. Fix retention first; growth follows.' },
    ],
  },
  {
    slug: 'daily-tech-ai-briefing-2026-08-17',
    title: 'Daily Tech & AI Briefing — 17 Agustus 2026',
    excerpt: 'Anthropic pecah rekor pendapatan $65M, Nvidia bet $21M di SpaceX, peretas target pengguna Apple masif, plus update AI & infra lain.',
    category: 'AI',
    readTime: '5 min',
    date: '2026-08-17',
    tags: ['AI', 'Industry', 'Briefing', 'Funding', 'Security'],
    content: [
      { type: 'p', text: 'Berikut ringkasan berita teknologi & AI hari ini yang patut diperhatikan:' },
      { type: 'h2', text: '🏆 Anthropic Pecah Rekor: $65M Pendapatan Tahunan' },
      { type: 'p', text: 'Anthropic melaporkan pendapatan tahunan (ARR) $65 juta — lompatan besar dari $10M setahun lalu. Ini sinyal permintaan enterprise untuk model frontier (Claude Opus/Sonnet) tetap sangat kuat, meski persaingan harga dari kompetitor Cina (DeepSeek, Alibaba) makin sengit.' },
      { type: 'h2', text: '🚀 Nvidia Taruh $21M di SpaceX' },
      { type: 'p', text: 'Nvidia mengungkap posisi investasi $21 juta di SpaceX, memperkuat taruhan jangka panjang pada infrastruktur antariksa Elon Musk. Kombinasi GPU Nvidia + satelit Starlink + roket Starship = stack komputasi terdistribusi skala planet.' },
      { type: 'h2', text: '🔴 Peretas Target Pengguna Apple Secara Masif' },
      { type: 'p', text: 'Kampanye phishing & malware besar-besaran menargeti Apple ID & iCloud. Vektor: SMS palsu (smishing) & email "verifikasi akun" yang mengarah ke halaman login clone. Aktifkan 2FA hardware key (YubiKey) & jangan klik link dari SMS/email tidak diketahui.' },
      { type: 'h2', text: '💡 Implikasi untuk Builder & Tim Produk' },
      { type: 'ul', items: [
        'Model jadi komoditas — diferensiasi pindah ke workflow, eval, dan domain data',
        'Infrastruktur AI (routing, billing, observability) capture value yang dulu di layer model',
        'Keamanan akun jadi tanggung jawab produk — jangan asumsikan user paham phishing',
        'Physical-world AI (robotics, autonomy, space compute) = frontier deployment baru',
      ]},
      { type: 'p', text: 'Pola konsisten: kecerdasan jadi infrastructure, nilai akumulasi ke yang wrap jadi workflow domain-specific yang reliable.' },
    ],
  },
  {
    slug: 'daily-tech-ai-briefing-2026-08-21',
    title: 'Daily Tech & AI Briefing — 21 Agustus 2026',
    excerpt: 'Micro1 capai $500M GRR di boom data training AI, Google Pixel 11 hadir AI penuh, Waymo robotaxi buka untuk semua rider, plus update AI & infra lain.',
    category: 'AI',
    readTime: '5 min',
    date: '2026-08-21',
    tags: ['AI', 'Industry', 'Briefing', 'Funding', 'Consumer Tech'],
    content: [
      { type: 'p', text: 'Berikut ringkasan berita teknologi & AI hari ini yang patut diperhatikan:' },
      { type: 'h2', text: '📈 Micro1 Capai $500M GRR: Boom Data Training AI' },
      { type: 'p', text: 'Startup data AI Micro1 melaporkan Gross Run Rate $500 juta, didorong lonjakan permintaan data training berkualitas tinggi. Ini menandakan pasar data AI — yang dulunya considered commodity — kini jadi bottleneck strategis. Kompetitor seperti Scale AI, Snorkel, dan Labelbox juga melihat pertumbuhan mirip.' },
      { type: 'h2', text: '📱 Google Pixel 11: AI Penuh di Genggaman' },
      { type: 'p', text: 'Pixel 11 Pro/Pro XL meluncur dengan Gemini terintegrasi mendalam: pesan makanan otomatis, booking layanan, editing foto generatif, dan voice typing yang "pure magic" menurut reviewer. Namun performa gaming masih di bawah pesaing, dan rear LED masih gimmick.' },
      { type: 'h2', text: '🚗 Waymo Robotaxi Buka untuk Semua Rider di 3 Kota' },
      { type: 'p', text: 'Waymo meluncurkan robotaxi next-gen yang lebih murah ke publik umum di San Francisco, Phoenix, dan Los Angeles. Milestone regulasi & operasional: pertama kalinya robotaxi mass-market berbagi jalan dengan lalu lintas normal tanpa safety driver.' },
      { type: 'h2', text: '💡 Implikasi untuk Builder & Tim Produk' },
      { type: 'ul', items: [
        'Data training jadi moat baru — model jadi komoditas, diferensiasi pindah ke kualitas & curation data',
        'Consumer AI: "AI yang benar-benar bekerja" (bukan chat) jadi expectation baru — Pixel 11 set bar',
        'Autonomous deployment: regulasi & kepercayaan publik sekarang bottleneck, bukan tech',
        'Infrastruktur AI (routing, billing, observability, data pipeline) capture value yang dulu di layer model',
      ]},
      { type: 'p', text: 'Pola konsisten: kecerdasan jadi infrastructure, nilai akumulasi ke yang wrap jadi workflow domain-specific yang reliable.' },
    ],
  },
  {
    slug: 'daily-tech-ai-briefing-2026-08-22',
    title: 'Daily Tech & AI Briefing — 22 Agustus 2026',
    excerpt: 'China AI boom di Inner Mongolia & Tesla recall terbesar karena door handles — dua sinyal infrastruktur & hardware yang membentuk era AI.',
    category: 'AI',
    readTime: '3 min',
    date: '2026-08-22',
    tags: ['AI', 'Industry', 'Briefing', 'China', 'Tesla', 'Infrastructure'],
    content: [
      { type: 'p', text: 'Berikut ringkasan berita teknologi & AI hari ini yang patut diperhatikan:' },
      { type: 'h2', text: '🏭 The Unlikely Place at the Center of China\'s AI Boom (WIRED)' },
      { type: 'p', text: 'Cheap energy, abundant land, and proximity to Beijing have turned a city in Inner Mongolia into a crucial hub for data centers. Ini mengungkap bagaimana infrastruktur fisik — listrik murah, lahan luas, akses ke kebijakan — jadi keunggulan kompetitif nyata di balik AI boom. Bukan cuma model, tapi di mana model itu di-train dan di-serve.' },
      { type: 'h2', text: '🚗 Tesla\'s Door Handles Lead to Its Biggest Recall Yet (WIRED)' },
      { type: 'p', text: 'A Chinese agency says Tesla\'s retractable door handles pose a safety risk in crashes — doors can jam shut, trapping occupants. Recall mencakup ratusan ribu unit Model S/X. Ini mengingatkan bahwa hardware complexity (door handles otomatis) bisa jadi liability saat safety critical, dan regulasi Cina kini lebih agresif memaksa recall massal.' },
      { type: 'h2', text: '💡 Implikasi untuk Builder & Tim Produk' },
      { type: 'ul', items: [
        'Infrastruktur AI (energy, land, cooling) jadi moat geografis — bukan cuma GPU',
        'Hardware complexity = surface area failure — simple, mechanical fallback matters di safety-critical',
        'Regulasi Cina gerak cepat & massal — compliance bukan optional, adalah product requirement',
        'Value capture bergeser ke layer physical: energy, real estate, logistics, hardware reliability',
      ]},
      { type: 'p', text: 'Pola konsisten: kecerdasan jadi infrastructure, nilai akumulasi ke yang wrap jadi workflow domain-specific yang reliable.' },
    ],
  },
  {
    slug: 'daily-tech-ai-briefing-2026-08-29',
    title: 'Daily Tech & AI Briefing — 29 Agustus 2026',
    excerpt: 'Chinese automakers ikut race humanoid robots, Tesla Optimus target produksi massal, plus update AI & infra lain.',
    category: 'AI',
    readTime: '5 min',
    date: '2026-08-29',
    tags: ['AI', 'Industry', 'Briefing', 'Robotics', 'China'],
    content: [
      { type: 'p', text: 'Berikut ringkasan berita teknologi & AI hari ini yang patut diperhatikan:' },
      { type: 'h2', text: '🤖 Chinese Automakers Ikut Race Humanoid Robots (TechCrunch)' },
      { type: 'p', text: 'Technical progress has encouraged a new batch of companies to jump in on the promise of profits from humanoid robots — and they are all Chinese automakers. BYD, Geely, Xpeng, and Nio are pouring R&D into bipedal robots, seeing the same TAM Tesla projects for Optimus. The logic: automotive supply chains (motors, batteries, actuators, compute) map 1:1 to humanoid hardware. China\'s manufacturing density lets them iterate faster.' },
      { type: 'h2', text: '🏭 Tesla Optimus: Target Produksi Massal 2026' },
      { type: 'p', text: 'Musk reiterasi Optimus akan mulai produksi massal di akhir 2026 untuk internal use, 2027 untuk external sales. Harga target <$20K. Jika tercapai, ini jadi inflection point: robot jadi affordable untuk factory/logistics, bukan cuma R&D toy. Key risk: hand dexterity & real-world reliability masih jauh dari human-level.' },
      { type: 'h2', text: '💡 Implikasi untuk Builder & Tim Produk' },
      { type: 'ul', items: [
        'Humanoid hardware supply chain = automotive supply chain — siapa punya skala manufaktur, dia menang',
        'China advantage: density, speed, government backing — watch BYD/Xpeng/Nio bukan cuma Tesla',
        'Robotics jadi deployment frontier selanjutnya setelah LLM — physical intelligence > chat intelligence',
        'Infrastruktur AI (energy, compute, manufacturing) capture value yang dulu di layer model',
      ]},
      { type: 'p', text: 'Pola konsisten: kecerdasan jadi infrastructure, nilai akumulasi ke yang wrap jadi workflow domain-specific yang reliable.' },
    ],
  },
]

export function getPost(slug: string) {
  return POSTS.find((p) => p.slug === slug)
}